# Generated by Django 4.0.5 on 2022-06-30 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('rank', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('link', models.URLField()),
                ('statement', models.TextField()),
                ('num_submissions', models.IntegerField(default=0)),
                ('num_ac', models.IntegerField(default=0)),
                ('num_wa', models.IntegerField(default=0)),
                ('num_re', models.IntegerField(default=0)),
                ('num_tle', models.IntegerField(default=0)),
                ('num_ce', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.IntegerField(default=1)),
                ('source', models.CharField(max_length=255)),
                ('num_tests', models.IntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.coder')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to=judge.models.in_upload_path)),
                ('output_file', models.FileField(upload_to=judge.models.out_upload_path)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TL', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('AC', 'Accepted')], default='NT', max_length=2)),
                ('lang', models.CharField(choices=[('C', 'GNU C'), ('CPP', 'GNU C++')], default='C', max_length=4)),
                ('code', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.problem')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.coder')),
            ],
        ),
        migrations.AddField(
            model_name='coder',
            name='problems_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='problems_ac', to='judge.problem'),
        ),
        migrations.AddField(
            model_name='coder',
            name='problems_tried',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='problems_tried', to='judge.problem'),
        ),
        migrations.AddField(
            model_name='coder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
